package com.sqeteam.sqerecruitment.pojo;
// Generated Apr 7, 2017 2:45:05 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EducationalQualifications generated by hbm2java
 */
@Entity
@Table(name="educational_qualifications"
    ,catalog="sqe_recruitment"
)
public class EducationalQualifications  implements java.io.Serializable {


     private Integer idEducationalQualifications;
     private EducationLevels educationLevels;
     private Persons persons;
     private String qualificationType;
     private String courseName;
     private Boolean vocational;
     private String mainSubject;
     private String nameOfInstitutions;
     private String country;
     private Date yearObtained;
     private String result;
     private String thesesTitle;
     private Boolean verified;
     private String howVerified;

    public EducationalQualifications() {
    }

	
    public EducationalQualifications(Persons persons, String qualificationType, String courseName) {
        this.persons = persons;
        this.qualificationType = qualificationType;
        this.courseName = courseName;
    }
    public EducationalQualifications(EducationLevels educationLevels, Persons persons, String qualificationType, String courseName, Boolean vocational, String mainSubject, String nameOfInstitutions, String country, Date yearObtained, String result, String thesesTitle, Boolean verified, String howVerified) {
       this.educationLevels = educationLevels;
       this.persons = persons;
       this.qualificationType = qualificationType;
       this.courseName = courseName;
       this.vocational = vocational;
       this.mainSubject = mainSubject;
       this.nameOfInstitutions = nameOfInstitutions;
       this.country = country;
       this.yearObtained = yearObtained;
       this.result = result;
       this.thesesTitle = thesesTitle;
       this.verified = verified;
       this.howVerified = howVerified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEducationalQualifications", unique=true, nullable=false)
    public Integer getIdEducationalQualifications() {
        return this.idEducationalQualifications;
    }
    
    public void setIdEducationalQualifications(Integer idEducationalQualifications) {
        this.idEducationalQualifications = idEducationalQualifications;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EducationLevels_idEducationLevel")
    public EducationLevels getEducationLevels() {
        return this.educationLevels;
    }
    
    public void setEducationLevels(EducationLevels educationLevels) {
        this.educationLevels = educationLevels;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Persons_idUser", nullable=false)
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }

    
    @Column(name="qualificationType", nullable=false, length=16)
    public String getQualificationType() {
        return this.qualificationType;
    }
    
    public void setQualificationType(String qualificationType) {
        this.qualificationType = qualificationType;
    }

    
    @Column(name="courseName", nullable=false, length=100)
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    
    @Column(name="vocational")
    public Boolean getVocational() {
        return this.vocational;
    }
    
    public void setVocational(Boolean vocational) {
        this.vocational = vocational;
    }

    
    @Column(name="mainSubject", length=45)
    public String getMainSubject() {
        return this.mainSubject;
    }
    
    public void setMainSubject(String mainSubject) {
        this.mainSubject = mainSubject;
    }

    
    @Column(name="nameOfInstitutions", length=100)
    public String getNameOfInstitutions() {
        return this.nameOfInstitutions;
    }
    
    public void setNameOfInstitutions(String nameOfInstitutions) {
        this.nameOfInstitutions = nameOfInstitutions;
    }

    
    @Column(name="country", length=45)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="yearObtained", length=10)
    public Date getYearObtained() {
        return this.yearObtained;
    }
    
    public void setYearObtained(Date yearObtained) {
        this.yearObtained = yearObtained;
    }

    
    @Column(name="result", length=20)
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }

    
    @Column(name="thesesTitle", length=200)
    public String getThesesTitle() {
        return this.thesesTitle;
    }
    
    public void setThesesTitle(String thesesTitle) {
        this.thesesTitle = thesesTitle;
    }

    
    @Column(name="verified")
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    
    @Column(name="howVerified", length=45)
    public String getHowVerified() {
        return this.howVerified;
    }
    
    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }




}


