package com.sqeteam.sqerecruitment.pojo;
// Generated Apr 7, 2017 2:45:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EducationLevels generated by hbm2java
 */
@Entity
@Table(name="education_levels"
    ,catalog="sqe_recruitment"
)
public class EducationLevels  implements java.io.Serializable {


     private Short idEducationLevel;
     private String educationLevel;
     private Set<EducationalQualifications> educationalQualificationses = new HashSet<EducationalQualifications>(0);
     private Set<Persons> personses = new HashSet<Persons>(0);

    public EducationLevels() {
    }

	
    public EducationLevels(String educationLevel) {
        this.educationLevel = educationLevel;
    }
    public EducationLevels(String educationLevel, Set<EducationalQualifications> educationalQualificationses, Set<Persons> personses) {
       this.educationLevel = educationLevel;
       this.educationalQualificationses = educationalQualificationses;
       this.personses = personses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEducationLevel", unique=true, nullable=false)
    public Short getIdEducationLevel() {
        return this.idEducationLevel;
    }
    
    public void setIdEducationLevel(Short idEducationLevel) {
        this.idEducationLevel = idEducationLevel;
    }

    
    @Column(name="educationLevel", nullable=false, length=100)
    public String getEducationLevel() {
        return this.educationLevel;
    }
    
    public void setEducationLevel(String educationLevel) {
        this.educationLevel = educationLevel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="educationLevels")
    public Set<EducationalQualifications> getEducationalQualificationses() {
        return this.educationalQualificationses;
    }
    
    public void setEducationalQualificationses(Set<EducationalQualifications> educationalQualificationses) {
        this.educationalQualificationses = educationalQualificationses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="educationLevels")
    public Set<Persons> getPersonses() {
        return this.personses;
    }
    
    public void setPersonses(Set<Persons> personses) {
        this.personses = personses;
    }




}


