package com.sqeteam.sqerecruitment.pojo;
// Generated Apr 7, 2017 2:45:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmploymentLevels generated by hbm2java
 */
@Entity
@Table(name="employment_levels"
    ,catalog="sqe_recruitment"
)
public class EmploymentLevels  implements java.io.Serializable {


     private Short idLevelsOfEmployment;
     private String employmentLevel;
     private Set<Experiences> experienceses = new HashSet<Experiences>(0);

    public EmploymentLevels() {
    }

	
    public EmploymentLevels(String employmentLevel) {
        this.employmentLevel = employmentLevel;
    }
    public EmploymentLevels(String employmentLevel, Set<Experiences> experienceses) {
       this.employmentLevel = employmentLevel;
       this.experienceses = experienceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idLevelsOfEmployment", unique=true, nullable=false)
    public Short getIdLevelsOfEmployment() {
        return this.idLevelsOfEmployment;
    }
    
    public void setIdLevelsOfEmployment(Short idLevelsOfEmployment) {
        this.idLevelsOfEmployment = idLevelsOfEmployment;
    }

    
    @Column(name="employmentLevel", nullable=false, length=45)
    public String getEmploymentLevel() {
        return this.employmentLevel;
    }
    
    public void setEmploymentLevel(String employmentLevel) {
        this.employmentLevel = employmentLevel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employmentLevels")
    public Set<Experiences> getExperienceses() {
        return this.experienceses;
    }
    
    public void setExperienceses(Set<Experiences> experienceses) {
        this.experienceses = experienceses;
    }




}


