package com.sqeteam.sqerecruitment.pojo;
// Generated Apr 7, 2017 1:28:55 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JobTitles generated by hbm2java
 */
@Entity
@Table(name = "job_titles")
public class JobTitles implements java.io.Serializable {

    @Id
    @Column
    private Short idJobTitles;
    @Column
    private Sectors sectors;
    @Column
    private String jobTitle;
    @Column
    private Set<Experiences> experienceses = new HashSet<Experiences>(0);
    @Column
    private Set<Persons> personses = new HashSet<Persons>(0);

    public JobTitles() {
    }

    public JobTitles(Sectors sectors, String jobTitle, Set<Experiences> experienceses, Set<Persons> personses) {
        this.sectors = sectors;
        this.jobTitle = jobTitle;
        this.experienceses = experienceses;
        this.personses = personses;
    }

    public Short getIdJobTitles() {
        return this.idJobTitles;
    }

    public void setIdJobTitles(Short idJobTitles) {
        this.idJobTitles = idJobTitles;
    }

    public Sectors getSectors() {
        return this.sectors;
    }

    public void setSectors(Sectors sectors) {
        this.sectors = sectors;
    }

    public String getJobTitle() {
        return this.jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public Set<Experiences> getExperienceses() {
        return this.experienceses;
    }

    public void setExperienceses(Set<Experiences> experienceses) {
        this.experienceses = experienceses;
    }

    public Set<Persons> getPersonses() {
        return this.personses;
    }

    public void setPersonses(Set<Persons> personses) {
        this.personses = personses;
    }

}
