package com.sqeteam.sqerecruitment.pojo;
// Generated Apr 7, 2017 2:45:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JobTitles generated by hbm2java
 */
@Entity
@Table(name="job_titles"
    ,catalog="sqe_recruitment"
)
public class JobTitles  implements java.io.Serializable {


     private Short idJobTitles;
     private Sectors sectors;
     private String jobTitle;
     private Set<Experiences> experienceses = new HashSet<Experiences>(0);
     private Set<Persons> personses = new HashSet<Persons>(0);

    public JobTitles() {
    }

    public JobTitles(Sectors sectors, String jobTitle, Set<Experiences> experienceses, Set<Persons> personses) {
       this.sectors = sectors;
       this.jobTitle = jobTitle;
       this.experienceses = experienceses;
       this.personses = personses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idJobTitles", unique=true, nullable=false)
    public Short getIdJobTitles() {
        return this.idJobTitles;
    }
    
    public void setIdJobTitles(Short idJobTitles) {
        this.idJobTitles = idJobTitles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Sectors_idSectors")
    public Sectors getSectors() {
        return this.sectors;
    }
    
    public void setSectors(Sectors sectors) {
        this.sectors = sectors;
    }

    
    @Column(name="jobTitle", length=45)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jobTitles")
    public Set<Experiences> getExperienceses() {
        return this.experienceses;
    }
    
    public void setExperienceses(Set<Experiences> experienceses) {
        this.experienceses = experienceses;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="job_preferences", catalog="sqe_recruitment", joinColumns = { 
        @JoinColumn(name="JobTitles_idJobTitles", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="person_idUser", nullable=false, updatable=false) })
    public Set<Persons> getPersonses() {
        return this.personses;
    }
    
    public void setPersonses(Set<Persons> personses) {
        this.personses = personses;
    }




}


