package com.sqeteam.sqerecruitment.pojo;
// Generated Apr 7, 2017 2:45:05 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProfessionalQualifications generated by hbm2java
 */
@Entity
@Table(name="professional_qualifications"
    ,catalog="sqe_recruitment"
)
public class ProfessionalQualifications  implements java.io.Serializable {


     private Integer idProfessionalQualifications;
     private Persons persons;
     private Sectors sectors;
     private String qualificationName;
     private String otherSector;
     private String awardingBody;
     private Date yearObtained;
     private String result;
     private Boolean verified;
     private String howVerified;

    public ProfessionalQualifications() {
    }

	
    public ProfessionalQualifications(Persons persons, String qualificationName) {
        this.persons = persons;
        this.qualificationName = qualificationName;
    }
    public ProfessionalQualifications(Persons persons, Sectors sectors, String qualificationName, String otherSector, String awardingBody, Date yearObtained, String result, Boolean verified, String howVerified) {
       this.persons = persons;
       this.sectors = sectors;
       this.qualificationName = qualificationName;
       this.otherSector = otherSector;
       this.awardingBody = awardingBody;
       this.yearObtained = yearObtained;
       this.result = result;
       this.verified = verified;
       this.howVerified = howVerified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProfessionalQualifications", unique=true, nullable=false)
    public Integer getIdProfessionalQualifications() {
        return this.idProfessionalQualifications;
    }
    
    public void setIdProfessionalQualifications(Integer idProfessionalQualifications) {
        this.idProfessionalQualifications = idProfessionalQualifications;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Persons_idUser", nullable=false)
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Sectors_idSectors")
    public Sectors getSectors() {
        return this.sectors;
    }
    
    public void setSectors(Sectors sectors) {
        this.sectors = sectors;
    }

    
    @Column(name="qualificationName", nullable=false, length=100)
    public String getQualificationName() {
        return this.qualificationName;
    }
    
    public void setQualificationName(String qualificationName) {
        this.qualificationName = qualificationName;
    }

    
    @Column(name="otherSector", length=45)
    public String getOtherSector() {
        return this.otherSector;
    }
    
    public void setOtherSector(String otherSector) {
        this.otherSector = otherSector;
    }

    
    @Column(name="awardingBody", length=45)
    public String getAwardingBody() {
        return this.awardingBody;
    }
    
    public void setAwardingBody(String awardingBody) {
        this.awardingBody = awardingBody;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="yearObtained", length=10)
    public Date getYearObtained() {
        return this.yearObtained;
    }
    
    public void setYearObtained(Date yearObtained) {
        this.yearObtained = yearObtained;
    }

    
    @Column(name="result", length=20)
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }

    
    @Column(name="verified")
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    
    @Column(name="howVerified", length=45)
    public String getHowVerified() {
        return this.howVerified;
    }
    
    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }




}


