package com.sqeteam.sqerecruitment.pojo;
// Generated Apr 7, 2017 1:28:55 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProfessionalQualifications generated by hbm2java
 */
@Entity
@Table(name = "professional_qualifications")
public class ProfessionalQualifications implements java.io.Serializable {

    @Id
    @Column
    private Integer idProfessionalQualifications;
    @Column
    private Persons persons;
    @Column
    private Sectors sectors;
    @Column
    private String qualificationName;
    @Column
    private String otherSector;
    @Column
    private String awardingBody;
    @Column
    private Date yearObtained;
    @Column
    private String result;
    @Column
    private Boolean verified;
    @Column
    private String howVerified;

    public ProfessionalQualifications() {
    }

    public ProfessionalQualifications(Persons persons, String qualificationName) {
        this.persons = persons;
        this.qualificationName = qualificationName;
    }

    public ProfessionalQualifications(Persons persons, Sectors sectors, String qualificationName, String otherSector, String awardingBody, Date yearObtained, String result, Boolean verified, String howVerified) {
        this.persons = persons;
        this.sectors = sectors;
        this.qualificationName = qualificationName;
        this.otherSector = otherSector;
        this.awardingBody = awardingBody;
        this.yearObtained = yearObtained;
        this.result = result;
        this.verified = verified;
        this.howVerified = howVerified;
    }

    public Integer getIdProfessionalQualifications() {
        return this.idProfessionalQualifications;
    }

    public void setIdProfessionalQualifications(Integer idProfessionalQualifications) {
        this.idProfessionalQualifications = idProfessionalQualifications;
    }

    public Persons getPersons() {
        return this.persons;
    }

    public void setPersons(Persons persons) {
        this.persons = persons;
    }

    public Sectors getSectors() {
        return this.sectors;
    }

    public void setSectors(Sectors sectors) {
        this.sectors = sectors;
    }

    public String getQualificationName() {
        return this.qualificationName;
    }

    public void setQualificationName(String qualificationName) {
        this.qualificationName = qualificationName;
    }

    public String getOtherSector() {
        return this.otherSector;
    }

    public void setOtherSector(String otherSector) {
        this.otherSector = otherSector;
    }

    public String getAwardingBody() {
        return this.awardingBody;
    }

    public void setAwardingBody(String awardingBody) {
        this.awardingBody = awardingBody;
    }

    public Date getYearObtained() {
        return this.yearObtained;
    }

    public void setYearObtained(Date yearObtained) {
        this.yearObtained = yearObtained;
    }

    public String getResult() {
        return this.result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public Boolean getVerified() {
        return this.verified;
    }

    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    public String getHowVerified() {
        return this.howVerified;
    }

    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }

}
