package com.sqeteam.sqerecruitment.pojo;
// Generated Apr 7, 2017 1:28:55 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Referees generated by hbm2java
 */
@Entity
@Table(name = "referees")
public class Referees implements java.io.Serializable {

    @Id
    @Column
    private Integer idReferees;
    @Column
    private Persons persons;
    @Column
    private String title;
    @Column
    private String forename;
    @Column
    private String surname;
    @Column
    private String email;
    @Column
    private String contactPhone;
    @Column
    private String relationship;
    @Column
    private Boolean permissionToContact;
    @Column
    private Boolean permissionToStoreDetails;
    @Column
    private Boolean verified;
    @Column
    private String howVerified;
    @Column
    private byte[] referenceDoc;

    public Referees() {
    }

    public Referees(Persons persons, String forename, String surname) {
        this.persons = persons;
        this.forename = forename;
        this.surname = surname;
    }

    public Referees(Persons persons, String title, String forename, String surname, String email, String contactPhone, String relationship, Boolean permissionToContact, Boolean permissionToStoreDetails, Boolean verified, String howVerified, byte[] referenceDoc) {
        this.persons = persons;
        this.title = title;
        this.forename = forename;
        this.surname = surname;
        this.email = email;
        this.contactPhone = contactPhone;
        this.relationship = relationship;
        this.permissionToContact = permissionToContact;
        this.permissionToStoreDetails = permissionToStoreDetails;
        this.verified = verified;
        this.howVerified = howVerified;
        this.referenceDoc = referenceDoc;
    }

    public Integer getIdReferees() {
        return this.idReferees;
    }

    public void setIdReferees(Integer idReferees) {
        this.idReferees = idReferees;
    }

    public Persons getPersons() {
        return this.persons;
    }

    public void setPersons(Persons persons) {
        this.persons = persons;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getForename() {
        return this.forename;
    }

    public void setForename(String forename) {
        this.forename = forename;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getContactPhone() {
        return this.contactPhone;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    public String getRelationship() {
        return this.relationship;
    }

    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    public Boolean getPermissionToContact() {
        return this.permissionToContact;
    }

    public void setPermissionToContact(Boolean permissionToContact) {
        this.permissionToContact = permissionToContact;
    }

    public Boolean getPermissionToStoreDetails() {
        return this.permissionToStoreDetails;
    }

    public void setPermissionToStoreDetails(Boolean permissionToStoreDetails) {
        this.permissionToStoreDetails = permissionToStoreDetails;
    }

    public Boolean getVerified() {
        return this.verified;
    }

    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    public String getHowVerified() {
        return this.howVerified;
    }

    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }

    public byte[] getReferenceDoc() {
        return this.referenceDoc;
    }

    public void setReferenceDoc(byte[] referenceDoc) {
        this.referenceDoc = referenceDoc;
    }

}
