package com.sqeteam.sqerecruitment.pojo;
// Generated Apr 7, 2017 2:45:05 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Referees generated by hbm2java
 */
@Entity
@Table(name="referees"
    ,catalog="sqe_recruitment"
)
public class Referees  implements java.io.Serializable {


     private Integer idReferees;
     private Persons persons;
     private String title;
     private String forename;
     private String surname;
     private String email;
     private String contactPhone;
     private String relationship;
     private Boolean permissionToContact;
     private Boolean permissionToStoreDetails;
     private Boolean verified;
     private String howVerified;
     private byte[] referenceDoc;

    public Referees() {
    }

	
    public Referees(Persons persons, String forename, String surname) {
        this.persons = persons;
        this.forename = forename;
        this.surname = surname;
    }
    public Referees(Persons persons, String title, String forename, String surname, String email, String contactPhone, String relationship, Boolean permissionToContact, Boolean permissionToStoreDetails, Boolean verified, String howVerified, byte[] referenceDoc) {
       this.persons = persons;
       this.title = title;
       this.forename = forename;
       this.surname = surname;
       this.email = email;
       this.contactPhone = contactPhone;
       this.relationship = relationship;
       this.permissionToContact = permissionToContact;
       this.permissionToStoreDetails = permissionToStoreDetails;
       this.verified = verified;
       this.howVerified = howVerified;
       this.referenceDoc = referenceDoc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idReferees", unique=true, nullable=false)
    public Integer getIdReferees() {
        return this.idReferees;
    }
    
    public void setIdReferees(Integer idReferees) {
        this.idReferees = idReferees;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Persons_idUser", nullable=false)
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }

    
    @Column(name="title", length=10)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="forename", nullable=false, length=45)
    public String getForename() {
        return this.forename;
    }
    
    public void setForename(String forename) {
        this.forename = forename;
    }

    
    @Column(name="surname", nullable=false, length=45)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="contactPhone", length=16)
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    
    @Column(name="relationship", length=9)
    public String getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    
    @Column(name="permissionToContact")
    public Boolean getPermissionToContact() {
        return this.permissionToContact;
    }
    
    public void setPermissionToContact(Boolean permissionToContact) {
        this.permissionToContact = permissionToContact;
    }

    
    @Column(name="permissionToStoreDetails")
    public Boolean getPermissionToStoreDetails() {
        return this.permissionToStoreDetails;
    }
    
    public void setPermissionToStoreDetails(Boolean permissionToStoreDetails) {
        this.permissionToStoreDetails = permissionToStoreDetails;
    }

    
    @Column(name="verified")
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    
    @Column(name="howVerified", length=45)
    public String getHowVerified() {
        return this.howVerified;
    }
    
    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }

    
    @Column(name="referenceDoc")
    public byte[] getReferenceDoc() {
        return this.referenceDoc;
    }
    
    public void setReferenceDoc(byte[] referenceDoc) {
        this.referenceDoc = referenceDoc;
    }




}


