package com.sqeteam.sqerecruitment.pojo;
// Generated Apr 7, 2017 1:28:55 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sectors generated by hbm2java
 */
@Entity
@Table(name = "sectors")
public class Sectors implements java.io.Serializable {

    @Id
    @Column
    private Short idSectors;
    @Column
    private String sectorTitle;
    @Column
    private Set<JobTitles> jobTitleses = new HashSet<JobTitles>(0);
    @Column
    private Set<ProfessionalQualifications> professionalQualificationses = new HashSet<ProfessionalQualifications>(0);

    public Sectors() {
    }

    public Sectors(String sectorTitle, Set<JobTitles> jobTitleses, Set<ProfessionalQualifications> professionalQualificationses) {
        this.sectorTitle = sectorTitle;
        this.jobTitleses = jobTitleses;
        this.professionalQualificationses = professionalQualificationses;
    }

    public Short getIdSectors() {
        return this.idSectors;
    }

    public void setIdSectors(Short idSectors) {
        this.idSectors = idSectors;
    }

    public String getSectorTitle() {
        return this.sectorTitle;
    }

    public void setSectorTitle(String sectorTitle) {
        this.sectorTitle = sectorTitle;
    }

    public Set<JobTitles> getJobTitleses() {
        return this.jobTitleses;
    }

    public void setJobTitleses(Set<JobTitles> jobTitleses) {
        this.jobTitleses = jobTitleses;
    }

    public Set<ProfessionalQualifications> getProfessionalQualificationses() {
        return this.professionalQualificationses;
    }

    public void setProfessionalQualificationses(Set<ProfessionalQualifications> professionalQualificationses) {
        this.professionalQualificationses = professionalQualificationses;
    }

}
