package com.sqeteam.sqerecruitment.pojo;
// Generated Apr 7, 2017 2:45:05 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Skills generated by hbm2java
 */
@Entity
@Table(name="skills"
    ,catalog="sqe_recruitment"
    , uniqueConstraints = @UniqueConstraint(columnNames={"Persons_idUser", "skillName"}) 
)
public class Skills  implements java.io.Serializable {


     private Integer idSkills;
     private Persons persons;
     private String skillName;
     private String skillLevel;
     private Boolean verified;
     private String howVerified;

    public Skills() {
    }

	
    public Skills(Persons persons, String skillName) {
        this.persons = persons;
        this.skillName = skillName;
    }
    public Skills(Persons persons, String skillName, String skillLevel, Boolean verified, String howVerified) {
       this.persons = persons;
       this.skillName = skillName;
       this.skillLevel = skillLevel;
       this.verified = verified;
       this.howVerified = howVerified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSkills", unique=true, nullable=false)
    public Integer getIdSkills() {
        return this.idSkills;
    }
    
    public void setIdSkills(Integer idSkills) {
        this.idSkills = idSkills;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Persons_idUser", nullable=false)
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }

    
    @Column(name="skillName", nullable=false, length=100)
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }

    
    @Column(name="skillLevel", length=9)
    public String getSkillLevel() {
        return this.skillLevel;
    }
    
    public void setSkillLevel(String skillLevel) {
        this.skillLevel = skillLevel;
    }

    
    @Column(name="verified")
    public Boolean getVerified() {
        return this.verified;
    }
    
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    
    @Column(name="howVerified", length=45)
    public String getHowVerified() {
        return this.howVerified;
    }
    
    public void setHowVerified(String howVerified) {
        this.howVerified = howVerified;
    }




}


